import { describe, it, expect } from 'vitest';
import { generateCSV, formatReportMetadata } from '../export';

describe('generateCSV', () => {
  const columns = [
    { key: 'name', header: 'Device Name' },
    { key: 'assetNumber', header: 'Asset #' },
    { key: 'status', header: 'Current Status' },
  ];

  it('outputs BOM and header row when data is empty', () => {
    const csv = generateCSV([], columns);
    expect(csv.startsWith('\uFEFF')).toBe(true);
    expect(csv).toContain('"Device Name","Asset #","Current Status"');
  });

  it('formats rows with quotes and escapes embedded quotes', () => {
    const data = [
      { name: 'Monitor "Pro"', assetNumber: 'AST-100', status: 'operational' },
      { name: 'Pump, Syringe', assetNumber: 'AST-101', status: 'under_repair' },
    ];
    const csv = generateCSV(data, columns);
    expect(csv).toContain('"Monitor ""Pro"""');
    expect(csv).toContain('"Pump, Syringe"');
  });

  it('handles null and undefined values cleanly', () => {
    const data = [
      { name: 'Sensor', assetNumber: null, status: undefined },
    ];
    const csv = generateCSV(data, columns);
    expect(csv).toContain('"Sensor","",""');
  });
});

describe('formatReportMetadata', () => {
  it('formats report transparency header lines correctly', () => {
    const date = new Date('2026-09-01T12:00:00Z');
    const header = formatReportMetadata({
      reportType: 'inventory',
      filters: { departmentId: 'dept-123' },
      dateRange: { start: '2026-01-01', end: '2026-09-01' },
      timezone: 'UTC',
      generatedAt: date,
      generatedBy: 'Admin User',
    });

    expect(header).toContain('# Report Type: inventory');
    expect(header).toContain('# Generated By: Admin User');
    expect(header).toContain('# Date Range Start: 2026-01-01');
    expect(header).toContain('# Date Range End: 2026-09-01');
    expect(header).toContain('dept-123');
  });
});
