import { auth } from '@/lib/auth';
import { redirect } from 'next/navigation';
import { getReportHistory } from '@/lib/actions/report-history';
import { Card, CardContent } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, Clock, FileText } from 'lucide-react';
import Link from 'next/link';

export default async function ReportHistoryPage() {
  const session = await auth();
  if (!session) redirect('/login');

  const history = await getReportHistory();

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link href="/reports" className="text-muted-foreground hover:text-foreground inline-flex items-center gap-2">
          <ArrowLeft className="h-4 w-4" />
          <span className="hidden sm:inline">Back to Reports</span>
        </Link>
        <h1 className="text-2xl font-bold tracking-tight">Report History</h1>
      </div>

      {!history || history.length === 0 ? (
        <Card>
          <CardContent className="p-12 text-center text-muted-foreground flex flex-col items-center justify-center">
            <Clock className="h-12 w-12 mb-4 text-muted/50" />
            <p className="text-lg font-medium mb-1 text-foreground">No reports have been generated yet.</p>
            <p>Export a report to save it here.</p>
          </CardContent>
        </Card>
      ) : (
        <>
          <div className="grid gap-4 md:hidden">
            {history.map((report) => (
              <Card key={report.id}>
                <CardContent className="p-4 space-y-3">
                  <div className="flex justify-between items-start">
                    <div>
                      <div className="font-semibold">{report.title}</div>
                      <div className="text-xs text-muted-foreground capitalize">{report.reportType.replace('_', ' ')}</div>
                    </div>
                    <Badge variant="outline">{report.fileFormat?.toUpperCase() || 'CSV'}</Badge>
                  </div>
                  
                  <div className="text-sm space-y-1">
                    {report.dateRangeStart && report.dateRangeEnd && (
                      <div className="text-muted-foreground">
                        Range: {new Date(report.dateRangeStart).toLocaleDateString()} - {new Date(report.dateRangeEnd).toLocaleDateString()}
                      </div>
                    )}
                    <div className="flex items-center justify-between text-xs text-muted-foreground pt-2 border-t mt-2">
                      <span>By: {report.generatedByUser?.fullName || 'Unknown'}</span>
                      <span>{new Date(report.generatedAt).toLocaleString()}</span>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <div className="hidden md:block rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Report Details</TableHead>
                  <TableHead>Date Range</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Format</TableHead>
                  <TableHead className="text-right">Generated Date</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {history.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell>
                      <div className="font-medium">{report.title}</div>
                      <div className="text-xs text-muted-foreground capitalize">{report.reportType.replace('_', ' ')}</div>
                    </TableCell>
                    <TableCell className="text-muted-foreground text-sm">
                      {report.dateRangeStart && report.dateRangeEnd 
                        ? `${new Date(report.dateRangeStart).toLocaleDateString()} - ${new Date(report.dateRangeEnd).toLocaleDateString()}` 
                        : 'N/A'
                      }
                    </TableCell>
                    <TableCell className="text-sm">{report.generatedByUser?.fullName || 'Unknown'}</TableCell>
                    <TableCell>
                      <Badge variant="outline">{report.fileFormat?.toUpperCase() || 'CSV'}</Badge>
                    </TableCell>
                    <TableCell className="text-right text-muted-foreground text-sm">
                      {new Date(report.generatedAt).toLocaleString()}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </>
      )}
    </div>
  );
}
