// Generate CSV with BOM for Excel compatibility
export function generateCSV(data: Record<string, any>[], columns: { key: string; header: string }[]): string {
  const BOM = '\uFEFF';
  if (!data || data.length === 0) {
    return BOM + columns.map(c => `"${c.header.replace(/"/g, '""')}"`).join(',');
  }

  const headerRow = columns.map(c => `"${c.header.replace(/"/g, '""')}"`).join(',');
  const rows = data.map(row => 
    columns.map(c => {
      let val = row[c.key];
      if (val === null || val === undefined) val = '';
      return `"${String(val).replace(/"/g, '""')}"`;
    }).join(',')
  );

  return BOM + [headerRow, ...rows].join('\n');
}

// Format report metadata for transparency header
export function formatReportMetadata(params: {
  reportType: string;
  filters: Record<string, any>;
  dateRange?: { start?: string; end?: string };
  timezone: string;
  generatedAt: Date;
  generatedBy: string;
}): string {
  const lines = [
    `Report Type: ${params.reportType}`,
    `Generated At: ${params.generatedAt.toISOString()} (${params.timezone})`,
    `Generated By: ${params.generatedBy}`,
  ];
  
  if (params.dateRange?.start) lines.push(`Date Range Start: ${params.dateRange.start}`);
  if (params.dateRange?.end) lines.push(`Date Range End: ${params.dateRange.end}`);
  
  const filterEntries = Object.entries(params.filters).filter(([k, v]) => v !== undefined && k !== 'page' && k !== 'pageSize' && k !== 'startDate' && k !== 'endDate' && k !== 'timezone');
  if (filterEntries.length > 0) {
    lines.push(`Filters: ${JSON.stringify(Object.fromEntries(filterEntries))}`);
  }
  
  return lines.map(line => `# ${line}`).join('\n') + '\n\n';
}
